### ISSUE TITLE
Docker plans?

### ISSUE THREAD

**Issue by OMGAmici** [vbrebion/rt_of_low_high_res_event_cameras#5]
Amazing work here, thank you!

Are there any plans or would there be any consideration made towards compiling your code into a Docker container to streamline set up?

**Comment by vbrebion** [comment]
Hi,

Thank you very much for your interest in our work!
And thank you for the idea, being able to compile / run the code in Docker should indeed simplify the set up for most users!

I am not an expert in Docker, but I think I have been able to create a Dockerfile which should answer the issue.
I have pushed it into a new `docker` branch, and the README has been updated to give instructions on how to compile and run the code with Docker.

Please do not hesitate to test it and to let me know if there is any issue / if you see any improvement that could be brought.
Once this is OK, I will merge https://github.com/heudiasyc/rt_of_low_high_res_event_cameras/pull/6 to add it to the main branch.

Best,
Vincent

**Comment by OMGAmici** [comment]
Thank you so much! This is a great addition. Just tried building the docker container and it went smoothly. 

One detail that others might run into depending on the machine they're working on is that line 13 in the Dockerfile might give issues due to certificate issues. If so, a quick fix I found was replacing it with `wget --no-check-certificate -qO - https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -`

**Comment by vbrebion** [comment]
Thank you for your comments!

I just fixed the potential certificate issue in <https://github.com/heudiasyc/rt_of_low_high_res_event_cameras/pull/6/commits/95649222230489d5abe4ad04b022867e1120ce94>.
Please do not hesitate to tell me if you think something else should be added/modified, or if I can merge it into `master`.

Best,
Vincent

**Comment by Stephen-Noblis** [comment]
I had no difficulty building and launching the container, but I'm finding that the launch files don't appear to find my dataset files. My dataset files are placed in the following structure:
```
|-----rt_of_low_high_res_event_cameras
|--launch
|--test_vids
|  |--prophesee
|  |  |--checkerboard.bag
|--src
....
```
When I run 
`roslaunch rt_of_low_high_res_event_cameras prophesee_gen4_replay.launch
`I run into...
`[ERROR] [1734025957.767291839]: Unknown input format dat/file, exiting!`

Where my launch XML looks like 
```
<launch>
  <!-- Edges node -->
  <node name="edges" pkg="rt_of_low_high_res_event_cameras" type="edges_node_replay" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="input_file" type="string" value="$(find rt_of_low_high_res_event_cameras)/test_vids/prophesee/checkerboard.bag"/>
    <param name="topic" type="string" value="/prophesee/camera/cd_events_buffer"/>
    <param name="accumulation_window" type="int" value="15"/>
    <param name="height" type="int" value="720"/>
    <param name="width" type="int" value="1280"/>
    <param name="queues_size" type="int" value="10000"/>
    <!--<param name="calibration_file" type="str" value="..."/>-->
  </node>

  <!-- Denoising & filling node -->
  <node name="denoising_filling" pkg="rt_of_low_high_res_event_cameras" type="denoising_filling_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="use_gpu_version" type="bool" value="true"/>
    <param name="denoising_min_neighbours" type="int" value="2"/>
    <param name="filling_min_neighbours" type="int" value="3"/>
    <param name="queues_size" type="int" value="10000"/>
  </node>

  <!-- Distance surface node -->
  <node name="distance_surface" pkg="rt_of_low_high_res_event_cameras" type="distance_surface_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="use_gpu_version" type="bool" value="true"/>
    <param name="distance_surface_formulation" type="string" value="exponential"/>
    <param name="queues_size" type="int" value="10000"/>
  </node>

  <!-- Optical flow node -->
  <node name="optical_flow" pkg="rt_of_low_high_res_event_cameras" type="optical_flow_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="pyramidal_flow_levels" type="int" value="3"/>
    <param name="max_flow" type="double" value="15.0"/>
    <rosparam param="gammas">[500.0, 500.0, 500.0]</rosparam>
    <rosparam param="smooth_iterations">[20, 20, 20]</rosparam>
    <param name="queues_size" type="int" value="10000"/>
  </node>

  <!-- Optical flow visualization node -->
  <node name="optical_flow_viz" pkg="rt_of_low_high_res_event_cameras" type="optical_flow_viz_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="visualization_method" type="string" value="colors"/>
    <param name="clip_flow" type="double" value="-1"/>
    <param name="queues_size" type="int" value="10000"/>
  </node>

  <!-- Display -->
  <node name="image_view" pkg="rqt_image_view" type="rqt_image_view" args="/rt_of_low_high_res_event_cameras/optical_flow_viz"/>

</launch>
```
All I've modified here is the **input_file** parameter under the **edge** node. I was unsure whether this was a ROS versioning issue? Thank you for your time.

Best,
Stephen

**Comment by vbrebion** [comment]
Thank you for reporting the issue!

The `Unknown input format dat/file, exiting!` error should only appear for a launch file in which the `input_file` has not been set (because the default value for this field is `/path/to/.bag/or/.dat/file`, and since the code looks at what is after the last `.` to determine the extension of the file (to know if it is a rosbag / DAT file / ...), it says here that it does not recognize the `.dat/file` extension).\
But you are right, the error message is probably not very clear, I will update the code to improve it.

However, since this value is correctly set in the launch file that you show, you should not have this issue.

Just to check something: have you maybe modified this launch file on the host *after* building the container?
Because when the container is built, all the files in the folder are **copied** to the container (line 43 of the Dockerfile):

```dockerfile
COPY ./ /catkin_ws/src/rt_of_low_high_res_event_cameras/
```

So, if it is indeed your issue, you should either modify the launch file directly in the container every time you run it (not very practical), or instead modify the launch file on the host and compile the container again.

The ideal solution would be instead to have the folder symbolically linked to the container, such that any modification that is made on the host (in the launch files for instance) would be visible in the container.

However, after looking into it, I do not think that it is something you can really do within the Dockerfile (you can only mount/bind a host directory when running the container).

So, if you have any suggestion on how the best way to solve this problem, please do not hesitate to suggest them!

Best,
Vincent

**Comment by Stephen-Noblis** [comment]
Thanks for the quick response!

It turns out that this specific error was indeed because I altered the file path after loading by mistake--thanks for suggesting that. However, rebuilding the container it seems my main issue is not yet resolved (though the `[ERROR] [1734025957.767291839]: Unknown input format dat/file, exiting!` statement is now absent):

`could not connect to display 
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`

Presumably the file path is correct now, but there still appears to be a package issue. Any guesses on what might be happening here? Thanks again for your time and help. 

Best,
Stephen

**Comment by vbrebion** [comment]
Hi again,

Glad that you were able to solve the first issue!

Regarding the second issue, it happens because the application is trying to open a graphical window for displaying the results, which is not possible with Docker in its default configuration.\
To avoid this issue, as noted in the README, you can instead use [rocker](https://github.com/osrf/rocker) to run the container, which takes care of this issue.

To install rocker:
```bash
pip install rocker
```

To launch the container with rocker:
```
rocker --nvidia --x11 --home rt_of_low_high_res_event_cameras
```

Please to not hesitate to tell me if this solves your issue!

Best,
Vincent

**Comment by Stephen-Noblis** [comment]
I am currently following those steps, so there seems to be another issue.

**Comment by vbrebion** [comment]
Hi,

This is surprising indeed.

Could you post the full log of what is displayed in the terminal after running the `rocker --nvidia --x11 --home rt_of_low_high_res_event_cameras` command and after running the launch file?
This would help me better track the issue.

Best,
Vincent

**Comment by Stephen-Noblis** [comment]
Hi Vincent, 

Thanks for the response. After entering 
`docker build -t rt_of_low_high_res_event_cameras .`
I get,

```
[+] Building 221.5s (34/34) FINISHED                                                                                                                                                          
 => [internal] load build definition from Dockerfile                                                                                                                                     0.0s
 => => transferring dockerfile: 2.32kB                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:12.6.2-devel-ubuntu20.04                                                                                                          0.1s
 => [internal] load build context                                                                                                                                                        0.0s
 => => transferring context: 6.63kB                                                                                                                                                      0.0s
 => [ 1/30] FROM docker.io/nvidia/cuda:12.6.2-devel-ubuntu20.04@sha256:4530850d4ab58f12b611da7bcceb7f4402f94e16b773c7c4b5358941ddea7e32                                                  0.0s
 => CACHED [ 2/30] RUN apt update                                                                                                                                                        0.0s
 => CACHED [ 3/30] RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y build-essential git nano software-properties-common tzdata wget                                          0.0s
 => CACHED [ 4/30] RUN echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list                                                                0.0s
 => CACHED [ 5/30] RUN wget --no-check-certificate -qO - https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -                                                  0.0s
 => CACHED [ 6/30] RUN apt update                                                                                                                                                        0.0s
 => CACHED [ 7/30] RUN apt install -y ros-noetic-ros-base ros-noetic-catkin ros-noetic-rqt-image-view python3-catkin-tools                                                               0.0s
 => CACHED [ 8/30] RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc                                                                                                             0.0s
 => CACHED [ 9/30] RUN source ~/.bashrc                                                                                                                                                  0.0s
 => CACHED [10/30] RUN git clone https://github.com/jadarve/optical-flow-filter.git                                                                                                      0.0s
 => CACHED [11/30] WORKDIR /optical-flow-filter                                                                                                                                          0.0s
 => CACHED [12/30] RUN mkdir build                                                                                                                                                       0.0s
 => CACHED [13/30] WORKDIR /optical-flow-filter/build                                                                                                                                    0.0s
 => CACHED [14/30] RUN cmake ..                                                                                                                                                          0.0s
 => CACHED [15/30] RUN make install                                                                                                                                                      0.0s
 => CACHED [16/30] RUN mkdir -p catkin_ws/src                                                                                                                                            0.0s
 => CACHED [17/30] WORKDIR /catkin_ws                                                                                                                                                    0.0s
 => CACHED [18/30] RUN catkin config --init --mkdirs --extend /opt/ros/noetic --merge-devel --cmake-args -DCMAKE_BUILD_TYPE=Release                                                      0.0s
 => CACHED [19/30] RUN add-apt-repository ppa:inivation-ppa/inivation                                                                                                                    0.0s
 => CACHED [20/30] RUN apt install -y libcaer-dev ros-noetic-cv-bridge ros-noetic-image-common                                                                                           0.0s
 => CACHED [21/30] WORKDIR /catkin_ws/src                                                                                                                                                0.0s
 => CACHED [22/30] RUN git clone https://github.com/catkin/catkin_simple.git                                                                                                             0.0s
 => CACHED [23/30] RUN git clone https://github.com/uzh-rpg/rpg_dvs_ros.git                                                                                                              0.0s
 => CACHED [24/30] RUN mkdir /catkin_ws/src/rt_of_low_high_res_event_cameras                                                                                                             0.0s
 => CACHED [25/30] WORKDIR /catkin_ws/src/rt_of_low_high_res_event_cameras                                                                                                               0.0s
 => [26/30] COPY ./ /catkin_ws/src/rt_of_low_high_res_event_cameras/                                                                                                                   110.1s
 => [27/30] WORKDIR /catkin_ws                                                                                                                                                           0.0s
 => [28/30] RUN catkin build rt_of_low_high_res_event_cameras                                                                                                                           21.4s
 => [29/30] RUN echo "source devel/setup.bash" >> ~/.bashrc                                                                                                                              0.8s
 => exporting to image                                                                                                                                                                  88.9s 
 => => exporting layers                                                                                                                                                                 88.9s 
 => => writing image sha256:bbc27c208832217a6d7370f7bc5eb9b30f664cf7e2cf8e85683eca5e237c3e1b                                                                                             0.0s 
 => => naming to docker.io/library/rt_of_low_high_res_event_cameras       
```

Then running rocker: `rocker --nvidia --x11 --home rt_of_low_high_res_event_cameras`

```
Extension volume doesn't support default arguments. Please extend it.
Active extensions ['home', 'nvidia', 'x11']
Step 1/6 : FROM golang:1.19 as detector
 ---> 80b76a6c918c
Step 2/6 : RUN git clone -q https://github.com/dekobon/distro-detect.git &&     cd distro-detect &&     git checkout -q 5f5b9c724b9d9a117732d2a4292e6288905734e1 &&     CGO_ENABLED=0 go build .
 ---> Using cache
 ---> 498635122878
Step 3/6 : FROM rt_of_low_high_res_event_cameras
 ---> bbc27c208832
Step 4/6 : COPY --from=detector /go/distro-detect/distro-detect /tmp/detect_os
 ---> 3b7c47b3465b
Step 5/6 : ENTRYPOINT [ "/tmp/detect_os", "-format", "json-one-line" ]
 ---> Running in e23d6ea1e463
Removing intermediate container e23d6ea1e463
 ---> 0820a77a353a
Step 6/6 : CMD [ "" ]
 ---> Running in d688e3f29bfe
Removing intermediate container d688e3f29bfe
 ---> 925cc14ae7cb
Successfully built 925cc14ae7cb
Successfully tagged rocker:os_detect_rt_of_low_high_res_event_cameras
running,  docker run -it --rm 925cc14ae7cb
output:  {"name":"Ubuntu","id":"ubuntu","version":"20.04","lsb_release":{"DISTRIB_CODENAME":"focal","DISTRIB_DESCRIPTION":"Ubuntu 20.04.6 LTS","DISTRIB_ID":"Ubuntu","DISTRIB_RELEASE":"20.04"},"os_release":{"BUG_REPORT_URL":"https://bugs.launchpad.net/ubuntu/","HOME_URL":"https://www.ubuntu.com/","ID":"ubuntu","ID_LIKE":"debian","NAME":"Ubuntu","PRETTY_NAME":"Ubuntu 20.04.6 LTS","PRIVACY_POLICY_URL":"https://www.ubuntu.com/legal/terms-and-policies/privacy-policy","SUPPORT_URL":"https://help.ubuntu.com/","UBUNTU_CODENAME":"focal","VERSION":"20.04.6 LTS (Focal Fossa)","VERSION_CODENAME":"focal","VERSION_ID":"20.04"}}

Writing dockerfile to /tmp/tmp5h40tsbu/Dockerfile
vvvvvv
# Preamble from extension [home]

# Preamble from extension [nvidia]
# Ubuntu 16.04 with nvidia-docker2 beta opengl support
FROM nvidia/opengl:1.0-glvnd-devel-ubuntu18.04 as glvnd

# Preamble from extension [x11]


FROM rt_of_low_high_res_event_cameras
USER root
# Snippet from extension [home]

# Snippet from extension [nvidia]
RUN apt-get update && apt-get install -y --no-install-recommends \
    libglvnd0 \
    libgl1 \
    libglx0 \
    libegl1 \
    libgles2 \
    && rm -rf /var/lib/apt/lists/*
COPY --from=glvnd /usr/share/glvnd/egl_vendor.d/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json




ENV NVIDIA_VISIBLE_DEVICES ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES ${NVIDIA_DRIVER_CAPABILITIES:-all}

# Snippet from extension [x11]

# User Snippet from extension [home]

# User Snippet from extension [nvidia]

# User Snippet from extension [x11]


^^^^^^
Building docker file with arguments:  {'path': '/tmp/tmp5h40tsbu', 'rm': True, 'nocache': False, 'pull': False}
building > Step 1/7 : FROM nvidia/opengl:1.0-glvnd-devel-ubuntu18.04 as glvnd
building >  ---> 9d806b36b807
building > Step 2/7 : FROM rt_of_low_high_res_event_cameras
building >  ---> bbc27c208832
building > Step 3/7 : USER root
building >  ---> Running in 045016eb0c4a
building > Removing intermediate container 045016eb0c4a
building >  ---> 80236e3cc585
building > Step 4/7 : RUN apt-get update && apt-get install -y --no-install-recommends     libglvnd0     libgl1     libglx0     libegl1     libgles2     && rm -rf /var/lib/apt/lists/*
building >  ---> Running in 62c4308c1057
building > Hit:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
building > Hit:2 http://packages.ros.org/ros/ubuntu focal InRelease
building > Get:3 http://security.ubuntu.com/ubuntu focal-security InRelease [128 kB]
building > Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
building > Hit:5 http://ppa.launchpad.net/inivation-ppa/inivation/ubuntu focal InRelease
building > Get:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease [128 kB]
building > Get:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease [128 kB]
building > Get:8 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [4159 kB]
building > Get:9 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1568 kB]
building > Get:10 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [4596 kB]
building > Get:11 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [4123 kB]
building > Get:12 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [1279 kB]
building > Fetched 16.1 MB in 2s (8332 kB/s)
Reading package lists...
building > Reading package lists...
building > Building dependency tree...
building > 
Reading state information...
building > libegl1 is already the newest version (1.3.2-1~ubuntu0.20.04.2).
libegl1 set to manually installed.
libgl1 is already the newest version (1.3.2-1~ubuntu0.20.04.2).
libgl1 set to manually installed.
libglvnd0 is already the newest version (1.3.2-1~ubuntu0.20.04.2).
libglvnd0 set to manually installed.
libglx0 is already the newest version (1.3.2-1~ubuntu0.20.04.2).
libglx0 set to manually installed.
The following NEW packages will be installed:
building >   libgles2
building > 0 upgraded, 1 newly installed, 0 to remove and 24 not upgraded.
Need to get 15.6 kB of archives.
After this operation, 109 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libgles2 amd64 1.3.2-1~ubuntu0.20.04.2 [15.6 kB]
building > debconf: delaying package configuration, since apt-utils is not installed

building > Fetched 15.6 kB in 0s (62.6 kB/s)
building > Selecting previously unselected package libgles2:amd64.
(Reading database ...
(Reading database ... 35%ase ... 5%
(Reading database ... 55%ase ... 40%
building > (Reading database ... 60%
building > (Reading database ... 65%
building > (Reading database ... 70%
building > (Reading database ... 75%
building > (Reading database ... 80%
building > (Reading database ... 85%
building > (Reading database ... 90%
building > (Reading database ... 95%
(Reading database ... 80727 files and directories currently installed.)
building > Preparing to unpack .../libgles2_1.3.2-1~ubuntu0.20.04.2_amd64.deb ...
building > Unpacking libgles2:amd64 (1.3.2-1~ubuntu0.20.04.2) ...
building > Setting up libgles2:amd64 (1.3.2-1~ubuntu0.20.04.2) ...
building > Processing triggers for libc-bin (2.31-0ubuntu9.16) ...
building > Removing intermediate container 62c4308c1057
building >  ---> 253a8548f723
building > Step 5/7 : COPY --from=glvnd /usr/share/glvnd/egl_vendor.d/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json
building >  ---> 26716ea6a9c7
building > Step 6/7 : ENV NVIDIA_VISIBLE_DEVICES ${NVIDIA_VISIBLE_DEVICES:-all}
building >  ---> Running in 41c582d30b7f
building > Removing intermediate container 41c582d30b7f
building >  ---> 9305c05f2465
building > Step 7/7 : ENV NVIDIA_DRIVER_CAPABILITIES ${NVIDIA_DRIVER_CAPABILITIES:-all}
building >  ---> Running in 4c620947d496
building > Removing intermediate container 4c620947d496
building >  ---> b2b0db0d22a9
building > Successfully built b2b0db0d22a9
xauth:  file /home/m34361/.Xauthority does not exist
xauth: (argv):1:  bad display name "None" in "nlist" command
xauth: (argv):1:  unable to read any entries from file "(stdin)"
Executing command: 
docker run --rm -it -v /home/m34361:/home/m34361   --gpus all  -e DISPLAY -e TERM   -e QT_X11_NO_MITSHM=1   -e XAUTHORITY=/tmp/.dockerph5dzl7w.xauth -v /tmp/.dockerph5dzl7w.xauth:/tmp/.dockerph5dzl7w.xauth   -v /tmp/.X11-unix:/tmp/.X11-unix   -v /etc/localtime:/etc/localtime:ro  b2b0db0d22a9 
```
I suspect these lines from above are relevant:

`xauth:  file /home/m34361/.Xauthority does not exist
xauth: (argv):1:  bad display name "None" in "nlist" command
xauth: (argv):1:  unable to read any entries from file "(stdin)"`

But the output from the launch file is:

``started roslaunch server http://f90b14363b98:45789/``
```
SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.17.0
 * /rt_of_low_high_res_event_cameras/denoising_filling/denoising_min_neighbours: 2
 * /rt_of_low_high_res_event_cameras/denoising_filling/filling_min_neighbours: 3
 * /rt_of_low_high_res_event_cameras/denoising_filling/queues_size: 10000
 * /rt_of_low_high_res_event_cameras/denoising_filling/use_gpu_version: True
 * /rt_of_low_high_res_event_cameras/distance_surface/distance_surface_formulation: exponential
 * /rt_of_low_high_res_event_cameras/distance_surface/queues_size: 10000
 * /rt_of_low_high_res_event_cameras/distance_surface/use_gpu_version: True
 * /rt_of_low_high_res_event_cameras/edges/accumulation_window: 15
 * /rt_of_low_high_res_event_cameras/edges/height: 720
 * /rt_of_low_high_res_event_cameras/edges/input_file: /catkin_ws/src/rt...
 * /rt_of_low_high_res_event_cameras/edges/queues_size: 10000
 * /rt_of_low_high_res_event_cameras/edges/topic: /prophesee/camera...
 * /rt_of_low_high_res_event_cameras/edges/width: 1280
 * /rt_of_low_high_res_event_cameras/optical_flow/gammas: [500.0, 500.0, 50...
 * /rt_of_low_high_res_event_cameras/optical_flow/max_flow: 15.0
 * /rt_of_low_high_res_event_cameras/optical_flow/pyramidal_flow_levels: 3
 * /rt_of_low_high_res_event_cameras/optical_flow/queues_size: 10000
 * /rt_of_low_high_res_event_cameras/optical_flow/smooth_iterations: [20, 20, 20]
 * /rt_of_low_high_res_event_cameras/optical_flow_viz/clip_flow: -1.0
 * /rt_of_low_high_res_event_cameras/optical_flow_viz/queues_size: 10000
 * /rt_of_low_high_res_event_cameras/optical_flow_viz/visualization_method: colors

NODES
  /
    image_view (rqt_image_view/rqt_image_view)
  /rt_of_low_high_res_event_cameras/
    denoising_filling (rt_of_low_high_res_event_cameras/denoising_filling_node)
    distance_surface (rt_of_low_high_res_event_cameras/distance_surface_node)
    edges (rt_of_low_high_res_event_cameras/edges_node_replay)
    optical_flow (rt_of_low_high_res_event_cameras/optical_flow_node)
    optical_flow_viz (rt_of_low_high_res_event_cameras/optical_flow_viz_node)

auto-starting new master
process[master]: started with pid [77]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 01b1edb8-bbc2-11ef-8910-0242ac110002
process[rosout-1]: started with pid [87]
started core service [/rosout]
process[rt_of_low_high_res_event_cameras/edges-2]: started with pid [94]
process[rt_of_low_high_res_event_cameras/denoising_filling-3]: started with pid [95]
process[rt_of_low_high_res_event_cameras/distance_surface-4]: started with pid [96]
process[rt_of_low_high_res_event_cameras/optical_flow-5]: started with pid [97]
process[rt_of_low_high_res_event_cameras/optical_flow_viz-6]: started with pid [98]
process[image_view-7]: started with pid [99]
could not connect to display 
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

[image_view-7] process has died [pid 99, exit code -11, cmd /opt/ros/noetic/lib/rqt_image_view/rqt_image_view /rt_of_low_high_res_event_cameras/optical_flow_viz __name:=image_view __log:=/root/.ros/log/01b1edb8-bbc2-11ef-8910-0242ac110002/image_view-7.log].
log file: /root/.ros/log/01b1edb8-bbc2-11ef-8910-0242ac110002/image_view-7*.log
FlowFilter::compute(): fisrt load
DeltaFlowFilter::compute(): fisrt load
DeltaFlowFilter::compute(): fisrt load
[rt_of_low_high_res_event_cameras/edges-2] process has finished cleanly
log file: /root/.ros/log/01b1edb8-bbc2-11ef-8910-0242ac110002/rt_of_low_high_res_event_cameras-edges-2*.log
`

```

Thank you for your time!

**Comment by Stephen-Noblis** [comment]
After working with my remote server, I was able to resolve the .xauth error above (failed X11 installation & permissions), but not the ROS failure. Here's my current approach and output:

1. build docker image: `docker build -t rt_of_low_high_res_event_cameras .`
2. launch with rocker: `rocker --nvidia --x11 --home rt_of_low_high_res_event_cameras`

> Extension volume doesn't support default arguments. Please extend it.
> Active extensions ['home', 'nvidia', 'x11']
> Step 1/6 : FROM golang:1.19 as detector
>  ---> 80b76a6c918c
> Step 2/6 : RUN git clone -q https://github.com/dekobon/distro-detect.git &&     cd distro-detect &&     git checkout -q 5f5b9c724b9d9a117732d2a4292e6288905734e1 &&     CGO_ENABLED=0 go build .
>  ---> Using cache
>  ---> 9f5854432728
> Step 3/6 : FROM rt_of_low_high_res_event_cameras
>  ---> 744f7bee39d3
> Step 4/6 : COPY --from=detector /go/distro-detect/distro-detect /tmp/detect_os
>  ---> 5963beb69576
> Step 5/6 : ENTRYPOINT [ "/tmp/detect_os", "-format", "json-one-line" ]
>  ---> Running in d6178de01333
> Removing intermediate container d6178de01333
>  ---> b71add748815
> Step 6/6 : CMD [ "" ]
>  ---> Running in 2c040dc288a9
> Removing intermediate container 2c040dc288a9
>  ---> 231f817e8866
> Successfully built 231f817e8866
> Successfully tagged rocker:os_detect_rt_of_low_high_res_event_cameras
> running,  docker run -it --rm 231f817e8866
> output:  {"name":"Ubuntu","id":"ubuntu","version":"20.04","lsb_release":{"DISTRIB_CODENAME":"focal","DISTRIB_DESCRIPTION":"Ubuntu 20.04.6 LTS","DISTRIB_ID":"Ubuntu","DISTRIB_RELEASE":"20.04"},"os_release":{"BUG_REPORT_URL":"https://bugs.launchpad.net/ubuntu/","HOME_URL":"https://www.ubuntu.com/","ID":"ubuntu","ID_LIKE":"debian","NAME":"Ubuntu","PRETTY_NAME":"Ubuntu 20.04.6 LTS","PRIVACY_POLICY_URL":"https://www.ubuntu.com/legal/terms-and-policies/privacy-policy","SUPPORT_URL":"https://help.ubuntu.com/","UBUNTU_CODENAME":"focal","VERSION":"20.04.6 LTS (Focal Fossa)","VERSION_CODENAME":"focal","VERSION_ID":"20.04"}}
> 
> Writing dockerfile to /tmp/tmpd4o53sod/Dockerfile
> vvvvvv
> \# Preamble from extension [home]
> 
> \# Preamble from extension [nvidia]
> \# Ubuntu 16.04 with nvidia-docker2 beta opengl support
> FROM nvidia/opengl:1.0-glvnd-devel-ubuntu18.04 as glvnd
> 
> \# Preamble from extension [x11]
> 
> 
> FROM rt_of_low_high_res_event_cameras
> USER root
> \# Snippet from extension [home]
> 
> \# Snippet from extension [nvidia]
> RUN apt-get update && apt-get install -y --no-install-recommends \
>     libglvnd0 \
>     libgl1 \
>     libglx0 \
>     libegl1 \
>     libgles2 \
>     && rm -rf /var/lib/apt/lists/*
> COPY --from=glvnd /usr/share/glvnd/egl_vendor.d/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json
> 
> 
> 
> 
> ENV NVIDIA_VISIBLE_DEVICES ${NVIDIA_VISIBLE_DEVICES:-all}
> ENV NVIDIA_DRIVER_CAPABILITIES ${NVIDIA_DRIVER_CAPABILITIES:-all}
> 
> \# Snippet from extension [x11]
> 
> \# User Snippet from extension [home]
> 
> \# User Snippet from extension [nvidia]
> 
> \# User Snippet from extension [x11]
> 
> 
> ^^^^^^
> Building docker file with arguments:  {'path': '/tmp/tmpd4o53sod', 'rm': True, 'nocache': False, 'pull': False}
> building > Step 1/7 : FROM nvidia/opengl:1.0-glvnd-devel-ubuntu18.04 as glvnd
> building >  ---> 9d806b36b807
> building > Step 2/7 : FROM rt_of_low_high_res_event_cameras
> building >  ---> 744f7bee39d3
> building > Step 3/7 : USER root
> building >  ---> Using cache
> building >  ---> 8e1c7ab9b56c
> building > Step 4/7 : RUN apt-get update && apt-get install -y --no-install-recommends     libglvnd0     libgl1     libglx0     libegl1     libgles2     && rm -rf /var/lib/apt/lists/*
> building >  ---> Using cache
> building >  ---> 524959222542
> building > Step 5/7 : COPY --from=glvnd /usr/share/glvnd/egl_vendor.d/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json
> building >  ---> Using cache
> building >  ---> e78305ae1ae7
> building > Step 6/7 : ENV NVIDIA_VISIBLE_DEVICES ${NVIDIA_VISIBLE_DEVICES:-all}
> building >  ---> Using cache
> building >  ---> e894b5b1bbab
> building > Step 7/7 : ENV NVIDIA_DRIVER_CAPABILITIES ${NVIDIA_DRIVER_CAPABILITIES:-all}
> building >  ---> Using cache
> building >  ---> 25fe35525fd6
> building > Successfully built 25fe35525fd6
> Executing command: 
> docker run --rm -it -v /home/m34361:/home/m34361   --gpus all  -e DISPLAY -e TERM   -e QT_X11_NO_MITSHM=1   -e XAUTHORITY=/tmp/.dockerbf575lwn.xauth -v /tmp/.dockerbf575lwn.xauth:/tmp/.dockerbf575lwn.xauth   -v /tmp/.X11-unix:/tmp/.X11-unix   -v /etc/localtime:/etc/localtime:ro  25fe35525fd6 
> 
> == CUDA ==
> 
> CUDA Version 12.6.2
> 
> Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
> 
> This container image and its contents are governed by the NVIDIA Deep Learning Container License.
> By pulling and using the container, you accept the terms and conditions of this license:
> https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
> 
> A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

4. run ROS launch file: `roslaunch rt_of_low_high_res_event_cameras prophesee_gen4_replay.launch `

> started roslaunch server http://3e605b98ddee:33589/
> 
> SUMMARY
> 
> 
> PARAMETERS
>  * /rosdistro: noetic
>  * /rosversion: 1.17.0
>  * /rt_of_low_high_res_event_cameras/denoising_filling/denoising_min_neighbours: 2
>  * /rt_of_low_high_res_event_cameras/denoising_filling/filling_min_neighbours: 3
>  * /rt_of_low_high_res_event_cameras/denoising_filling/queues_size: 10000
>  * /rt_of_low_high_res_event_cameras/denoising_filling/use_gpu_version: True
>  * /rt_of_low_high_res_event_cameras/distance_surface/distance_surface_formulation: exponential
>  * /rt_of_low_high_res_event_cameras/distance_surface/queues_size: 10000
>  * /rt_of_low_high_res_event_cameras/distance_surface/use_gpu_version: True
>  * /rt_of_low_high_res_event_cameras/edges/accumulation_window: 15
>  * /rt_of_low_high_res_event_cameras/edges/height: 720
>  * /rt_of_low_high_res_event_cameras/edges/input_file: /catkin_ws/src/rt...
>  * /rt_of_low_high_res_event_cameras/edges/queues_size: 10000
>  * /rt_of_low_high_res_event_cameras/edges/topic: /prophesee/camera...
>  * /rt_of_low_high_res_event_cameras/edges/width: 1280
>  * /rt_of_low_high_res_event_cameras/optical_flow/gammas: [500.0, 500.0, 50...
>  * /rt_of_low_high_res_event_cameras/optical_flow/max_flow: 15.0
>  * /rt_of_low_high_res_event_cameras/optical_flow/pyramidal_flow_levels: 3
>  * /rt_of_low_high_res_event_cameras/optical_flow/queues_size: 10000
>  * /rt_of_low_high_res_event_cameras/optical_flow/smooth_iterations: [20, 20, 20]
>  * /rt_of_low_high_res_event_cameras/optical_flow_viz/clip_flow: -1.0
>  * /rt_of_low_high_res_event_cameras/optical_flow_viz/queues_size: 10000
>  * /rt_of_low_high_res_event_cameras/optical_flow_viz/visualization_method: colors
> 
> NODES
>   /
>     image_view (rqt_image_view/rqt_image_view)
>   /rt_of_low_high_res_event_cameras/
>     denoising_filling (rt_of_low_high_res_event_cameras/denoising_filling_node)
>     distance_surface (rt_of_low_high_res_event_cameras/distance_surface_node)
>     edges (rt_of_low_high_res_event_cameras/edges_node_replay)
>     optical_flow (rt_of_low_high_res_event_cameras/optical_flow_node)
>     optical_flow_viz (rt_of_low_high_res_event_cameras/optical_flow_viz_node)
> 
> auto-starting new master
> process[master]: started with pid [77]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to ddba9d28-cc57-11ef-8fa0-0242ac110002
> process[rosout-1]: started with pid [87]
> started core service [/rosout]
> process[rt_of_low_high_res_event_cameras/edges-2]: started with pid [90]
> process[rt_of_low_high_res_event_cameras/denoising_filling-3]: started with pid [91]
> process[rt_of_low_high_res_event_cameras/distance_surface-4]: started with pid [92]
> process[rt_of_low_high_res_event_cameras/optical_flow-5]: started with pid [93]
> process[rt_of_low_high_res_event_cameras/optical_flow_viz-6]: started with pid [97]
> process[image_view-7]: started with pid [99]
> could not connect to display localhost:14.0
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
> 
> [image_view-7] process has died [pid 99, exit code -11, cmd /opt/ros/noetic/lib/rqt_image_view/rqt_image_view /rt_of_low_high_res_event_cameras/optical_flow_viz __name:=image_view __log:=/root/.ros/log/ddba9d28-cc57-11ef-8fa0-0242ac110002/image_view-7.log].
> log file: /root/.ros/log/ddba9d28-cc57-11ef-8fa0-0242ac110002/image_view-7*.log
> terminate called after throwing an instance of 'rosbag::BagIOException'
>   what():  Error reading from file: wanted 4 bytes, read 0 bytes
> [rt_of_low_high_res_event_cameras/edges-2] process has died [pid 90, exit code -6, cmd /catkin_ws/devel/lib/rt_of_low_high_res_event_cameras/edges_node_replay __name:=edges __log:=/root/.ros/log/ddba9d28-cc57-11ef-8fa0-0242ac110002/rt_of_low_high_res_event_cameras-edges-2.log].
> log file: /root/.ros/log/ddba9d28-cc57-11ef-8fa0-0242ac110002/rt_of_low_high_res_event_cameras-edges-2*.log


Which seems to suggest a persistent issue with connecting to display (`could not connect to display localhost:14.0`).

**Comment by vbrebion** [comment]
Hi,

Thank you very much for the logs, and I am glad you were able to solve the issue with `xauth`!

As for the `could not connect to display localhost:14.0` message, this indicates that there is still an issue with your X11 setup.
However, I cannot really help you with that, as it highly depends on your configuration.

The following thread offers several answers, maybe one of them can help you: <https://superuser.com/q/310197>
To also help you in diagnosing the issue, instead of using the full `roslaunch rt_of_low_high_res_event_cameras prophesee_gen4_replay.launch` command, you can also just run the `rqt_image_view -v` command in the container (this is the part that fails in the full launchfile, and the `-v` may give you more verbose information for debugging).

Please do not hesitate to share here if you find a solution, or if you have any further isssue!

Best,
Vincent

**Comment by vbrebion** [comment]
Hi,

Given that there has been no further issue raised, I am merging <https://github.com/heudiasyc/rt_of_low_high_res_event_cameras/pull/6> in `master`, so that everyone can use the Dockerfile (thanks again for the idea @OMGAmici 😄).

Please do not hesitate to open a new issue if you have any problem or question regarding the use of Docker with our code!

Best,
Vincent
